from re import L


import sys
import os
import re

def main():
    ToC = {"Foreword to the Revised Edition": "#0000016509", 
        "There Are Monsters Out There": "#0000019997", 
        "What You've Signed Up For": "#0000022081", 
        "What You'll Need": "#0000023888", 
        "What You Should Read": "#0000027662", 
        "Structure": "#0000032412", 
        "Feedback": "#0000033243", 
        "The Hunters": "#0000035156", 
        "The First Session": "#0000035902", 
        "Extra hunter types": "#0000044270", 
        "Just One Of Each": "#0000048334", 
        "Making Your Hunter": "#0000049013", 
        "Team Concepts": "#0000050145", 
        "Team Customisation": "#0000051530", 
        "Example Team Concepts": "#0000053837", 
        "Slayer and Entourage": "#0000054201", 
        "The Unexplained Cases Team": "#0000054877", 
        "The Order": "#0000056190", 
        "Road-tripping Hunter Family": "#0000057394", 
        "Before You GET STARTED": "#0000058688", 
        "Moves": "#0000059416", 
        "The Hunter Basic Moves": "#0000062239", 
        "The Ratings": "#0000064752", 
        "The Playbooks": "#0000067792", 
        "The Crooked": "#0000090524", 
        "The Divine": "#0000113203", 
        "The Expert": "#0000130787", 
        "The Flake": "#0000150627", 
        "The Initiate": "#0000167603", 
        "The Mundane": "#0000213865", 
        "The Professional": "#0000231064", 
        "The Spell-Slinger": "#0000251948", 
        "The Spooky": "#0000273714", 
        "Get Ready For Action": "#0000316463", 
        "Introductions": "#0000317074", 
        "History": "#0000317700", 
        "How To Play": "#0000321613", 
        "Hunter Agenda": "#0000321886", 
        "The Game Is A Conversation": "#0000323626", 
        "Moves": "#0000325098", 
        "You Have To Make The Move": "#0000327888", 
        "Rolling the Dice": "#0000331862", 
        "Bonuses and Holds": "#0000333552", 
        "The Basic Moves": "#0000338319", 
        "Act Under Pressure": "#0000338728", 
        "Help Out": "#0000339930", 
        "Investigate A Mystery": "#0000341067", 
        "Kick Some Ass": "#0000344192", 
        "Manipulate Someone": "#0000346149", 
        "Protect Someone": "#0000350330", 
        "Read A Bad Situation": "#0000351890", 
        "Use Magic": "#0000354206", 
        "Big Magic": "#0000359101", 
        "Fights": "#0000363980", 
        "Unarmed Attacks And Improvised Weapons": "#0000365701", 
        "Harm": "#0000367151", 
        "Monsters and Harm": "#0000368731", 
        "Healing": "#0000370652", 
        "Healing Between Mysteries": "#0000373011", 
        "Resurrection": "#0000373673", 
        "The Luck Counter": "#0000377180", 
        "When You Run Out Of Luck": "#0000378193", 
        "Gear": "#0000378861", 
        "Getting New Gear": "#0000379148", 
        "Weapons": "#0000380474", 
        "Custom Weapons": "#0000387343", 
        "Armour": "#0000389349", 
        "Other Gear": "#0000390805", 
        "Gear Tags": "#0000391460", 
        "Custom Gear Moves": "#0000392083", 
        "Leveling Up": "#0000392979", 
        "End Of Session Experience": "#0000394218", 
        "Improvements": "#0000395352", 
        "Advanced Improvements": "#0000411668", 
        "Advanced Moves": "#0000419601", 
        "Playbook-Specific Advanced Improvements": "#0000424250", 
        "Summary: Hunter's Session": "#0000431162", 
        "The First Time Only": "#0000431524", 
        "Every Game": "#0000432976", 
        "The Keeper": "#0000434803", 
        "What You Do": "#0000435449", 
        "How It Will Play Out": "#0000436631", 
        "No Planning Ahead": "#0000437574", 
        "It's About the Hunters, Not The Mystery": "#0000439573", 
        "Before Your First Game": "#0000440629", 
        "Think About Style": "#0000441334", 
        "Get Into The Keeper Mindset": "#0000442528", 
        "The Keeper Agenda": "#0000443922", 
        "The Keeper Principles": "#0000444796", 
        "Creating Your First Mystery": "#0000446797", 
        "An Example Mystery Mongolian Death Worm Attack": "#0000449005", 
        "What That All Means": "#0000452333", 
        "Preparing Your First Mystery": "#0000461838", 
        "The Hook": "#0000463407", 
        "The Threats": "#0000464702", 
        "More Threats": "#0000492594", 
        "Mystery Countdowns": "#0000492975", 
        "Summary: First Mystery Creation": "#0000497784", 
        "Introductory Mystery: Dream Away the Time": "#0000500258", 
        "Mystery concept": "#0000501025", 
        "Hook": "#0000501825", 
        "Countdown": "#0000502884", 
        "Notes": "#0000503146", 
        "Threats": "#0000506553", 
        "Oberon, King of Faerie": "#0000506674", 
        "Oberon's Fortress": "#0000510750", 
        "Violet, a changeling": "#0000511868", 
        "Bonecruncher, a Redcap": "#0000514888", 
        "The Old Forest Nature Reserve, near Handfast": "#0000518221", 
        "Handfast, the Town": "#0000519320", 
        "Tornado And Flood Wreckage": "#0000520186", 
        "Handfast Children's Park": "#0000521052", 
        "Max Tilley, a beloved child": "#0000522058", 
        "Mary and Samuel Tilley, Max's parents": "#0000522557", 
        "John and Alice Chilton, Violet's parents": "#0000523611", 
        "Officer Edward Turner": "#0000525225", 
        "The Assault Victims": "#0000527477", 
        "Jane Howland, Editor of the Handfast Herald": "#0000529012", 
        "The Crowne Tavern": "#0000530190", 
        "Ely Holbeck, Bartender": "#0000530880", 
        "Decide who has the initiative": "#0000672235", 
        "Use The Environment": "#0000673623", 
        "Make Maps": "#0000675876"}
    sections = ["Foreword to the Revised Edition",
        "There Are Monsters Out There",
        "What You've Signed Up For",
        "What You'll Need",
        "What You Should Read",
        "Structure",
        "Feedback",
        "The Hunters",
        "The First Session",
        "Extra hunter types",
        "Just One Of Each",
        "Making Your Hunter",
        "Team Concepts",
        "Team Customisation",
        "Example Team Concepts",
        "Slayer and Entourage",
        "The Unexplained Cases Team",
        "The Order",
        "Roadtripping Hunter Family",
        "Before You GET STARTED",
        "Moves",
        "The Hunter Basic Moves",
        "The Ratings",
        "The Playbooks",
        "The Chosen",
        "The Crooked",
        "The Divine",
        "The Expert",
        "The Flake",
        "The Initiate",
        "The Monstrous",
        "The Mundane",
        "The Professional",
        "The SpellSlinger",
        "The Spooky",
        "The Wronged",
        "Get Ready For Action",
        "Introductions",
        "History",
        "How To Play",
        "Hunter Agenda",
        "The Game Is A Conversation",
        "Moves",
        "You Have To Make The Move",
        "Rolling the Dice",
        "Bonuses and Holds",
        "FORWARD",
        "ONGOING",
        "HOLD",
        "The Basic Moves",
        "Act Under Pressure",
        "Help Out",
        "Investigate A Mystery",
        "Kick Some Ass",
        "Manipulate Someone",
        "Protect Someone",
        "Read A Bad Situation",
        "Use Magic",
        "Big Magic",
        "Fights",
        "Unarmed Attacks And Improvised Weapons",
        "Harm",
        "Monsters and Harm    ",
        "Healing",
        "Healing Between Mysteries",
        "Resurrection",
        "The Luck Counter",
        "When You Run Out Of Luck",
        "Gear",
        "Getting New Gear",
        "Weapons",
        "Custom Weapons",
        "Armour",
        "Other Gear",
        "Gear Tags",
        "Custom Gear Moves",
        "Leveling Up",
        "End Of Session Experience",
        "Improvements",
        "Advanced Improvements",
        "Advanced Moves",
        "Playbook Specific Advanced Improvements",
        "Summary Hunter's Session",
        "The First Time Only",
        "Every Game",
        "The Keeper",
        "What You Do",
        "How It Will Play Out",
        "No Planning Ahead",
        "It's About the Hunters, Not The Mystery",
        "Before Your First Game",
        "Think About Style",
        "Get Into The Keeper Mindset",
        "The Keeper Agenda",
        "The Keeper Principles",
        "Creating Your First Mystery",
        "An Example Mystery Mongolian Death Worm Attack",
        "What That All Means",
        "Componenents of a mystery",
        "Preparing Your First Mystery",
        "The Hook",
        "The Threats",
        "Monsters",
        "Minions",
        "Bystanders",
        "Locations",
        "More Threats",
        "Mystery Countdowns",
        "Summary First Mystery Creation",
        "Introductory Mystery Dream Away the Time",
        "The First SesSion",
        "Hunter Creation",
        "Introductions",
        "History",
        "Running The First Mystery",
        "The Game Is A Conversation",
        "Keeper Agenda",
        "The Keeper Principles",
        "Always Say",
        "Moves",
        "The Basic Keeper Moves",
        "Using The Keeper Moves",
        "Which Keeper Move To Use",
        "Threat Moves",
        "The Basic Hunter Moves",
        "Act Under Pressure",
        "Help Out",
        "Investigate A Mystery",
        "Kick Some Ass",
        "Manipulate Someone",
        "Protect Someone",
        "Read A Bad Situation",
        "Use Magic",
        "Big Magic",
        "Playbook Moves",
        "Actions Not Covered By A Move",
        "On With The Mystery",
        "StartOfMystery Moves",
        "The Teaser",
        "Beginning the Investigation",
        "Use The Countdown",
        "I'm Not Prepared For This",
        "It Always Comes To A Fight",
        "Harm",
        "Healing",
        "An Example Fight",
        "End of the First Session",
        "Summary Keeper's First Session",
        "Between Game Sessions:  Arcs",
        "Building Arcs",
        "The Basic Concept",
        "Arc Threats",
        "Arc Countdowns",
        "Arc Templates",
        "Ancient Evil Rising",
        "The Nemesis",
        "The End of Days",
        "Corruption",
        "Arc Custom Moves",
        "Summary Arc Creation",
        "Between Game Sessions: Subsequent mysteries",
        "Summary: Mystery Creation    ",
        "Basic Concept",
        "The Hook",
        "The Threats",
        "The Countdown",
        "Messing With The Formula",
        "Sessions and Mysteries",
        "Mystery Letters",
        "Running Subsequent Mysteries",
        "At the Beginning of Each Session",
        "Playing the Mystery",
        "At the End of Each Session",
        "Summary Keeper's Session",
        "Mystery Damn Dirty Apes",
        "As the game  Goes On",
        "At the End Of Each Mystery",
        "Checking On Your Arcs",
        "Building Mythology",
        "Endgame",
        "Leveling Up And Improvements",
        "Running Out Of Luck",
        "Dealing With Arcs",
        "Other Things To Consider",
        "How To End A Game",
        "OneShot Games",
        "Player Numbers",
        "Customising Your Game",
        "Custom Moves",
        "Defining The Move",
        "Triggering The Custom Move",
        "Move Types",
        "Example Custom Moves",
        "Custom Threats",
        "Legacy Experience Rules",
        "Sharing The Keeper Duties",
        "Custom Playbooks",
        "A Whole New Game",
        "Inspiration",
        "Index"]
    # headings = [re.sub(r"[\\\/\:\"\*\?\<\>\|]", section) for section in sections]
    codes = {ToC[key]:key for key in ToC}
    not_allowed_in_file = r'[\\\/\:\"\*\?\<\>\|]'
    file_path = r"C:\Users\aweso\Documents\GitHub\Obsidian-notes\D&D\D&D\MOTW\Book"
    with open(file_path + r"\Monster_of_the_Week.md", 'r', encoding='utf-8') as f:
        text = f.readlines()
    file_path += r"\MOTW Sections"
    writing = open(file_path + r"\Monster_of_the_Week.md", 'w', encoding='utf-8')
    linked_text = ""
    for line in text:
        if line.strip() in sections:
            linked_text += f"[[{line.strip()}]]\n"
            writing.write(linked_text)
            writing.close()
            linked_text = ""
            writing = open(file_path + f"\\{re.sub(not_allowed_in_file, '', line).strip()}.md", 'a', encoding='utf-8')
        else:
            # m = re.match(r"\[\[\#(\d*)\]\]")
            linked_text += re.sub(r"\[\[\#(\d*)\]\]", r"[[\1]]", line)
    writing.close()
    # link_pattern = r"(\[here\]\(\#(\d*)\))"

    # linked_text = ""
    # for line in text:
    #     matches = re.findall(link_pattern, line)
    #     if len(matches) > 0:
    #         start = 0
    #         new_text = "" 
    #         for match in matches:
    #             substitute = f"[here]({match})"
    #             # new_text += line[start:match.start()]
    #             # new_text += f"[[{codes[match.group(1)]}]]"
    #             # start = match.end()
    #             try:
    #                 line = line.replace(match[0], f"[[{codes['#' + match[1]]}]]")
    #             except KeyError:
    #                 line = line.replace(match[0], f"[[{match[1]}]]" )
    #             new_text = line
    #     else:
    #         new_text = line
    #     linked_text += new_text
    # with open(file_path + r"\Monster_of_the_Week.md", 'w', encoding='utf-8') as nf:
    #     nf.write(linked_text)
    return 


if __name__ == '__main__':
    main()